### ISSUE TITLE
ISK5\2M550T-1014 ASCII parse error (weird characters in output)

### ISSUE THREAD

**Issue by vvmichielvv** [dsmrreader/dsmr-reader#2031]
### Language / Voertaal

🇬🇧 English

### Help yourself

- [X] I've checked [the how-to guides](https://dsmr-reader.readthedocs.io/nl/v5/how-to/index.html)
- [X] I've checked previous [questions](https://github.com/dsmrreader/dsmr-reader/discussions)
- [X] I've checked (recent) [previous issues](https://github.com/dsmrreader/dsmr-reader/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc) and their solutions
- [X] I've checked the [logfiles](https://dsmr-reader.readthedocs.io/nl/v5/how-to/troubleshooting/logfiles.html) *(when applicable)*

### Inquiry

Report a bug

### Description

I just recently got a new smartmeter in NL and try to readout the P1. I have configured it as V5: 

-    baudrate = 115200
-    parity=serial.PARITY_NONE
-    stopbits=serial.STOPBITS_ONE
-    bytesize=serial.EIGHTBITS

DSMR-reader fails to read it. When I write a small readout program myself using latin1 for decoding, i get text, but also many weird characters. Any idea?

### DSMR-reader version

5.11.0

### DSMR-reader platform

Native (e.g. manual installation)

### Optional: Debug info dump (of DSMR-reader)

```shell-script
for telegram in serial_reader.read():
  File "/usr/local/lib/python3.11/dist-packages/dsmr_parser/clients/serial_.py", line 34, in read
    self.telegram_buffer.append(data.decode('ascii'))
                                ^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8a in position 5: ordinal not in range(128)
```

### Optional: Smart meter telegram

```shell-script
/ISK5\2M550T-1014



1-3:0.2.8(50)

0-0:1.0.0(241023202130S)

0-0:96.1.1(4530&�Â�������Ê�������º�Ê���Ê���¢Jj

1-0:1.8.1(000012.NL�ië�¥

LKÒ�rÂr�B�����Êr�ÂªRZ]¡¥C¡j�Ò�rÂr�B������r��¢RZ]¡¥

1KÓ�rÂr�B�����Âr��²RZ]h)
0-0:N�)¢r�C����Kj

LKÒ�rºs�B��sÊª�R[]¥H(j�Ò�sºr�B��r���RZ]¥

0       ÓÊ²rºs��B����ªJk

0-0:96.7.9(00002)

1-0:99.97.0()

1-0:32.32.0(00000)

1-0:52.32.0(00000)

1-0:72.32.0(00000)

1-0:32.36.0(00000)

1-0:M&i²r�B�����Jj

1-0:�r�²r�B�����Jj

0-0:N�)�r�BJj

1-0:&&ér�B��Âr�R²¥C¡j�Òª�rºr�B���r�R²¥

1-0:72.�        B���rÊR²¥

1KÒ��rºr�B��ªR

¥

1-0:51.�        B���S

¥C¡j�Òº�rºr�C���R
                 ¥
1-0:31.7.0(00.875*kU©H(j�Ó¢�rºs�B��s��ºR[]¥H(j�Ò²�rºr�C��r�³ªRZ])

1-0:22.7.0(00.000*kW)

1-0:42.7.0(00.000*kW)

1-0:62.7.0(00.000*kW)

H35

/ISK5\2M550T-1014
```

**Comment by dennissiemensma** [comment]
Having weird characters usually is reflected by encryption, interference or a bad cable.

- Since some of the data is human readable (and no encryption applies in the Netherlands), you can assume encryption is not causing it
- The cables are really sensitive to interference, so make sure that you have nothing near that can cause it. E.g. a net power cable touching it, causing disturbance in the data sent
- The cable might be faulty too, but that is a hard one to presume, as *some* data seems to pass well. So don't take my word for it

Some other cases with *minor* issues (you really have large parts of data corrupt compared to those):
- https://github.com/dsmrreader/dsmr-reader/issues/1823#issuecomment-1464220267
- https://github.com/dsmrreader/dsmr-reader/issues/1733#issuecomment-1301244754
